server:
  port: 8086

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce
    username: ecommerce_user
    password: ecommerce_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

security:
  jwt:
    secret: my-super-secure-key-change-later